version: "3"
services:
  project-a:
    build: .
    command: "yarn start:dev"
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
  api:
    image: rodolpheche/wiremock
    ports:
      - 8080:8080
networks:
  default:
    external:
      name: wiremock-poc-network